<?php

return [
    'register' => static function (Router $router): void {
        $guestOnly = ['guest'];
        $authOnly = ['auth'];
        $adminOnly = ['role:admin'];
        $wholesaleOnly = ['role:admin,wholesale'];
        $nonWholesale = ['forbid:wholesale'];

        $router->get('home', [HomeController::class, 'index']);
        $router->get('catalog', [ProductController::class, 'catalog'], $authOnly);
        $router->get('cart', [CartController::class, 'index'], $authOnly);
        $router->get('subscription', [SubscriptionController::class, 'index'], $authOnly);
        $router->get('promo', [PromoController::class, 'index'], $nonWholesale);
        $router->get('wholesale', [WholesaleController::class, 'index'], $wholesaleOnly);
        $router->get('orders', [OrdersController::class, 'index'], $authOnly);
        $router->get('orders-history', [OrdersController::class, 'history'], $authOnly);
        $router->get('order-edit', [OrdersController::class, 'edit'], $authOnly);
        $router->get('order-payment', [OrdersController::class, 'payment'], $authOnly);
        $router->get('payment-result', [PaymentController::class, 'result']);
        $router->post('payment-result', [PaymentController::class, 'result']);
        $router->get('payment-success', [PaymentController::class, 'success']);
        $router->get('payment-fail', [PaymentController::class, 'fail']);
        $router->get('account', [AccountController::class, 'index'], $authOnly);
        $router->get('account-notifications', [AccountController::class, 'notifications'], $authOnly);
        $router->get('account-calendar', [AccountController::class, 'calendar'], $authOnly);
        $router->get('login', [AuthController::class, 'login'], $guestOnly);
        $router->get('logout', [AuthController::class, 'logout'], $authOnly);
        $router->get('register', [AuthController::class, 'register'], $guestOnly);
        $router->get('recover', [AuthController::class, 'recover'], $guestOnly);
        $router->get('policy', [LegalController::class, 'policy']);
        $router->get('consent', [LegalController::class, 'consent']);
        $router->get('offer', [LegalController::class, 'offer']);
        $router->get('about', [InfoController::class, 'about']);
        $router->get('roses', [InfoController::class, 'roses']);
        $router->get('delivery', [InfoController::class, 'delivery']);
        $router->get('discount', [InfoController::class, 'discount']);
        $router->get('static', [StaticPageController::class, 'show']);
        $router->get('admin', [AdminController::class, 'index'], $adminOnly);
        $router->get('admin-users', [AdminController::class, 'users'], $adminOnly);
        $router->get('admin-user', [AdminController::class, 'user'], $adminOnly);
        $router->get('admin-cashback', [AdminController::class, 'cashback'], $adminOnly);
        $router->get('admin-broadcast', [AdminController::class, 'broadcasts'], $adminOnly);
        $router->get('admin-group-create', [AdminController::class, 'groupCreate'], $adminOnly);
        $router->get('admin-products', [AdminController::class, 'catalogProducts'], $adminOnly);
        $router->get('admin-product-form', [AdminController::class, 'productForm'], $adminOnly);
        $router->get('admin-promos', [AdminController::class, 'catalogPromos'], $adminOnly);
        $router->get('admin-auction-create', [AdminController::class, 'auctionCreate'], $adminOnly);
        $router->get('admin-promo-item-create', [AdminController::class, 'promoItemCreate'], $adminOnly);
        $router->get('admin-lottery-create', [AdminController::class, 'lotteryCreate'], $adminOnly);
        $router->get('admin-promo-item-edit', [AdminController::class, 'promoItemEdit'], $adminOnly);
        $router->get('admin-lottery-edit', [AdminController::class, 'lotteryEdit'], $adminOnly);
        $router->get('admin-auction-edit', [AdminController::class, 'auctionEdit'], $adminOnly);
        $router->get('admin-auction-view', [AdminController::class, 'auctionView'], $adminOnly);
        $router->get('admin-attributes', [AdminController::class, 'catalogAttributes'], $adminOnly);
        $router->get('admin-supplies', [AdminController::class, 'catalogSupplies'], $adminOnly);
        $router->get('admin-supply-standing', [AdminController::class, 'supplyStandingForm'], $adminOnly);
        $router->get('admin-supply-single', [AdminController::class, 'supplySingleForm'], $adminOnly);
        $router->get('admin-supply-edit', [AdminController::class, 'editSupply'], $adminOnly);
        $router->get('admin-orders-one-time', [AdminController::class, 'ordersOneTime'], $adminOnly);
        $router->get('admin-order-one-time-edit', [AdminController::class, 'orderOneTimeEdit'], $adminOnly);
        $router->get('admin-orders-subscriptions', [AdminController::class, 'ordersSubscriptions'], $adminOnly);
        $router->get('admin-orders-wholesale', [AdminController::class, 'ordersWholesale'], $adminOnly);
        $router->get('admin-services-payment', [AdminController::class, 'serviceOnlinePayment'], $adminOnly);
        $router->get('admin-services-delivery', [AdminController::class, 'serviceDelivery'], $adminOnly);
        $router->get('admin-services-telegram', [AdminController::class, 'serviceTelegram'], $adminOnly);
        $router->get('admin-services-frontpad', [AdminController::class, 'serviceFrontpad'], $adminOnly);
        $router->get('admin-content-static', [AdminController::class, 'contentStatic'], $adminOnly);
        $router->get('admin-content-products', [AdminController::class, 'contentProducts'], $adminOnly);
        $router->get('admin-content-sections', [AdminController::class, 'contentSections'], $adminOnly);
        $router->post('api-dadata-clean-address', [ApiController::class, 'cleanDadataAddress']);
        $router->post('login', [AuthController::class, 'login'], $guestOnly);
        $router->post('register', [AuthController::class, 'register'], $guestOnly);
        $router->post('recover', [AuthController::class, 'recover'], $guestOnly);
        $router->post('admin-users-toggle', [AdminController::class, 'toggleUserActive'], $adminOnly);
        $router->post('admin-cashback-level-save', [AdminController::class, 'saveCashbackLevel'], $adminOnly);
        $router->post('admin-cashback-product-toggle', [AdminController::class, 'toggleCashbackProduct'], $adminOnly);
        $router->post('admin-cashback-promo-toggle', [AdminController::class, 'toggleCashbackPromo'], $adminOnly);
        $router->post('admin-group-create', [AdminController::class, 'saveGroup'], $adminOnly);
        $router->post('admin-broadcast', [AdminController::class, 'createBroadcast'], $adminOnly);
        $router->post('admin-user-role', [AdminController::class, 'updateUserRole'], $adminOnly);
        $router->post('admin-user-notifications', [AdminController::class, 'updateUserNotifications'], $adminOnly);
        $router->post('admin-user-broadcast-group', [AdminController::class, 'updateUserBroadcastGroup'], $adminOnly);
        $router->post('admin-supply-standing', [AdminController::class, 'createStandingSupply'], $adminOnly);
        $router->post('admin-supply-single', [AdminController::class, 'createSingleSupply'], $adminOnly);
        $router->post('admin-supply-update', [AdminController::class, 'updateSupply'], $adminOnly);
        $router->post('admin-supply-toggle-card', [AdminController::class, 'toggleSupplyCard'], $adminOnly);
        $router->post('admin-attribute-save', [AdminController::class, 'saveAttribute'], $adminOnly);
        $router->post('admin-attribute-delete', [AdminController::class, 'deleteAttribute'], $adminOnly);
        $router->post('admin-attribute-value-save', [AdminController::class, 'saveAttributeValue'], $adminOnly);
        $router->post('admin-attribute-value-delete', [AdminController::class, 'deleteAttributeValue'], $adminOnly);
        $router->post('admin-product-save', [AdminController::class, 'saveProduct'], $adminOnly);
        $router->post('admin-product-delete', [AdminController::class, 'deleteProduct'], $adminOnly);
        $router->post('admin-product-toggle', [AdminController::class, 'toggleProductActive'], $adminOnly);
        $router->post('admin-services-payment', [AdminController::class, 'saveServicePayment'], $adminOnly);
        $router->post('admin-services-telegram', [AdminController::class, 'saveServiceTelegram'], $adminOnly);
        $router->post('admin-services-frontpad', [AdminController::class, 'saveServiceFrontpad'], $adminOnly);
        $router->post('admin-services-delivery', [AdminController::class, 'saveServiceDelivery'], $adminOnly);
        $router->post('admin-lottery-save', [AdminController::class, 'saveLottery'], $adminOnly);
        $router->post('admin-lottery-update', [AdminController::class, 'updateLottery'], $adminOnly);
        $router->post('admin-auction-save', [AdminController::class, 'saveAuctionLot'], $adminOnly);
        $router->post('admin-auction-update', [AdminController::class, 'updateAuctionLot'], $adminOnly);
        $router->post('admin-promo-item-save', [AdminController::class, 'savePromoItem'], $adminOnly);
        $router->post('admin-promo-item-update', [AdminController::class, 'updatePromoItem'], $adminOnly);
        $router->post('admin-promo-categories-save', [AdminController::class, 'savePromoCategories'], $adminOnly);
        $router->post('admin-promo-settings-save', [AdminController::class, 'savePromoSettings'], $adminOnly);
        $router->post('admin-order-update', [AdminController::class, 'updateOneTimeOrder'], $adminOnly);
        $router->post('admin-order-delete', [AdminController::class, 'deleteOneTimeOrder'], $adminOnly);
        $router->post('admin-static-page-save', [AdminController::class, 'saveStaticPage'], $adminOnly);
        $router->post('admin-static-page-toggle', [AdminController::class, 'toggleStaticPage'], $adminOnly);
        $router->post('admin-static-page-delete', [AdminController::class, 'deleteStaticPage'], $adminOnly);
        $router->post('cart-add', [CartController::class, 'add']);
        $router->post('cart-update', [CartController::class, 'update']);
        $router->post('cart-remove', [CartController::class, 'remove']);
        $router->post('cart-checkout', [CartController::class, 'checkout'], $authOnly);
        $router->post('order-edit', [OrdersController::class, 'update'], $authOnly);
        $router->post('order-payment', [OrdersController::class, 'pay'], $authOnly);
        $router->post('account-notifications', [AccountController::class, 'updateNotifications'], $authOnly);
        $router->post('account-pin', [AccountController::class, 'updatePin'], $authOnly);
        $router->get('support-messages', [SupportController::class, 'listMessages']);
        $router->post('support-message', [SupportController::class, 'sendMessage']);
    },
];
