ALTER TABLE users
  ADD COLUMN tulip_balance INT NOT NULL DEFAULT 0 AFTER role;

CREATE TABLE cashback_levels (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  percent_single DECIMAL(5,2) NOT NULL DEFAULT 0,
  percent_pack DECIMAL(5,2) NOT NULL DEFAULT 0,
  percent_box DECIMAL(5,2) NOT NULL DEFAULT 0,
  percent_promo DECIMAL(5,2) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE products
  ADD COLUMN allow_tulip_spend TINYINT(1) NOT NULL DEFAULT 1 AFTER product_type,
  ADD COLUMN allow_tulip_earn TINYINT(1) NOT NULL DEFAULT 1 AFTER allow_tulip_spend;

ALTER TABLE promo_items
  ADD COLUMN allow_tulip_spend TINYINT(1) NOT NULL DEFAULT 1 AFTER price,
  ADD COLUMN allow_tulip_earn TINYINT(1) NOT NULL DEFAULT 1 AFTER allow_tulip_spend;
